### ISSUE TITLE
Paste support

### ISSUE THREAD

**Issue by ltrubov** [jbadger3/Terminus#3]
Hello:

I discovered this in the course of developing a command-line app using terminus: `Terminal` does not properly respond to pasting text -- or more precisely, to any text input of more than one character per command.

#### Reproduction

|   STR   | Expected result | Actual result | 
| :------------------: | :------------------------: | :----------------: |
| Create the `Terminal` object and listen to input via `LineEditor().getInput()` | Cursor is displayed, waiting for input | Cursor is displayed, waiting for input  | 
| Copy `foobar` text and paste in the terminal.  | `foobar` appears in the terminal, cursor moves ahead |`raboof` appears in the terminal, cursor moves ahead |
|  Press enter   | "foobar" is now read into the string assigned as return value to the `getInput()` method | "raboof" is now read into the string assigned as return value to the `getInput()` method |

As the above illustrates, the pasted string is displayed in the terminal and read into the input buffer -- and thus into any `String` returned and used in the app -- *in reverse*. This is a feature of buffer implementation. 

#### Temporary fix

I implemented a fix using a custom `characterKeyHandler` to the `LineEditor` instance by copying the default handler and adding special treatment for multicharacter strings:

```
extension LineEditor {
    public func promptCharacterHandler(_ characterString: String) -> (ShouldAddKeyToLineBuffer, ShouldWriteBuffer) {
            do {
                try "mclog: character input: \(characterString)".write(toFile: "\(NSHomeDirectory())/.mc_logs", atomically: true, encoding: .utf8)
            }catch {
                print(error)
            }
            if characterString == Backspace {
                let shouldWriteBuffer = defaultBackspaceKeyHandler()
                return (false, shouldWriteBuffer)
            }
            if characterString == Linefeed {
                shouldEndEditing = true
                return (false, false)
            }
            if characterString == Esc {
                return (false, false)
            }
            
            if characterString.count > 1 { //awkward way to (temporarily) handle paste
                guard let loc = Terminal.shared.cursor.location else { return }
                guard let bi = bufferIndexForLocation(loc) else { return }
                buffer.insert(AttributedString(stringLiteral: toPaste), at: bi)
                return (false, true)
            }
            return (true, true)
        }
}
```

However, this not the best solution, and does not handle multi-line pasting correctly.

Sorry if this comes across as overly critical. Terminus is a very useful tool and has helped me enormously, but I am not familiar enough with string buffer work to submit my own bug fix, so I'm bringing this to the attention of the software authors.

**Comment by jbadger3** [comment]
@ltrubov 
Thanks for bringing this bug to my attention.  I believe I have things fixed.  You can try out your code in the open PR I recently created.
